routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('organizzati', 'HomeController@howto')->name('howto');

Route::get('login', function() {
    if (Auth::check())
        return redirect()->route('local.index');
    else
        Aacotroneo\Saml2\Facades\Saml2Auth::login(route('home'));
})->name('login');

Route::get('login/gitlab', function() {
    return Socialite::driver('GitLab')->setScopes('read_user')->redirect();
})->name('login.gitlab');

Route::get('login/gitlab/callback', function() {
    $user = Socialite::driver('GitLab')->user();
    $extended_username = sprintf('gitlab_%s', $user->getNickname());

    $effective = App\User::where('username', $extended_username)->first();
    if ($effective == null) {
        $effective = App\User::where('email', $user->getEmail())->first();
        if ($effective == null) {
            $effective = new App\User();
            $effective->username = $extended_username;
            $effective->name = $user->getName();
            $effective->email = $user->getEmail();
            $effective->save();
        }
    }

    Auth::loginUsingId($effective->id);

    return redirect()->route('local.index');
})->name('login.callback_gitlab');

Route::get('login/facebook', function() {
    return Socialite::driver('facebook')->redirect();
})->name('login.facebook');

Route::get('login/facebook/callback', function() {
    $user = Socialite::driver('facebook')->user();
    $extended_username = sprintf('facebook_%s', $user->getNickname());

    $effective = App\User::where('username', $extended_username)->first();
    if ($effective == null) {
        $effective = App\User::where('email', $user->getEmail())->first();
        if ($effective == null) {
            $effective = new App\User();
            $effective->username = $extended_username;
            $effective->name = $user->getName();
            $effective->email = $user->getEmail();
            $effective->save();
        }
    }

    Auth::loginUsingId($effective->id);

    return redirect()->route('local.index');
})->name('login.callback_facebook');

Route::get('local/subscribe/{id}', 'LocalController@subscribe')->name('local.subscribe');

Route::resource('local', 'LocalController');

app/Devroom.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Devroom extends Model
{
    //
}

app/Local.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Local extends Model
{
    public function owner()
    {
        return $this->belongsTo('App\User');
    }

    public function devrooms()
    {
        return $this->belongsToMany('App\Devroom');
    }
}

app/Talk.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Talk extends Model
{
    public function users()
    {
        return $this->belongsToMany('App\User');
    }

    public function getStreamingUrlAttribute()
    {
        $tokens = explode(' ', $this->location);
        return sprintf('https://live.fosdem.org/watch/%s', str_slug($tokens[0]));
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    public function ownLocal()
    {
        return $this->hasMany('App\Local', 'owner_id');
    }

    public function getOwnAttribute()
    {
        return $this->ownLocal()->where('year', env('CURRENT_YEAR'))->first();
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

use Auth;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

    public function __construct()
    {
        //
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Auth;

class HomeController extends Controller
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }

    public function howto()
    {
        return view('howto');
    }
}

app/Http/Controllers/LocalController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Local;

class LocalController extends Controller
{
    public function index(Request $request)
    {
        $user = $request->user();
        $locals = Local::where('year', env('CURRENT_YEAR'))->orderBy('province', 'asc')->get();
        return view('local.index', compact('locals', 'user'));
    }

    public function create(Request $request)
    {
        $user = $request->user();
        if ($user == null)
            return redirect()->route('home');

        if ($user->own != null)
            return redirect()->route('local.show', $user->own->id);

        return view('local.create');
    }

    private function readFromRequest($local, $request)
    {
        $local->lng = $request->input('lng');
        $local->lat = $request->input('lat');
        $local->province = $request->input('province');
        $local->city = ucwords($request->input('city'));
        $local->address = ucwords($request->input('address'));
        $local->description = strip_tags($request->input('description'));
        $local->rooms = $request->input('rooms');

        $days = $request->input('days');
        switch($days) {
            case 'both':
                $local->has_saturday = true;
                $local->has_sunday = true;
                break;
            case 'saturday':
                $local->has_saturday = true;
                $local->has_sunday = false;
                break;
            case 'sunday':
                $local->has_saturday = false;
                $local->has_sunday = true;
                break;
        }
    }

    public function store(Request $request)
    {
        $request->validate([
            'lat' => 'required|numeric',
            'lng' => 'required|numeric',
            'province' => 'required|max:2',
            'city' => 'required|max:255',
            'address' => 'required|max:255',
            'description' => 'required',
            'days' => 'required',
            'rooms' => 'required|numeric',
        ]);

        $local = new Local();
        self::readFromRequest($local, $request);
        $local->year = env('CURRENT_YEAR');
        $local->approved = false;
        $local->owner_id = $request->user()->id;
        $local->save();

        $local->devrooms()->sync($request->input('devroom'));

        return redirect()->route('local.show', $local->id);
    }

    public function show(Request $request, $id)
    {
        $user = $request->user();
        $local = Local::findOrFail($id);
        return view('local.show', compact('local', 'user'));
    }

    public function edit(Request $request, $id)
    {
        $user = $request->user();
        if ($user == null)
            return redirect()->route('home');

        $local = Local::findOrFail($id);
        if ($local->owner_id != $user->id)
            return redirect()->route('home');

        return view('local.edit', compact('local'));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'lat' => 'required|numeric',
            'lng' => 'required|numeric',
            'province' => 'required|max:2',
            'city' => 'required|max:255',
            'address' => 'required|max:255',
            'description' => 'required',
            'days' => 'required',
            'rooms' => 'required|numeric',
        ]);

        $user = $request->user();
        if ($user == null)
            return redirect()->route('home');

        $local = Local::findOrFail($id);
        if ($local->owner_id != $user->id)
            return redirect()->route('home');

        self::readFromRequest($local, $request);
        $local->save();

        $local->devrooms()->sync($request->input('devroom'));

        return redirect()->route('local.show', $local->id);
    }

    public function destroy(Request $request, $id)
    {
        $user = $request->user();
        $local = Local::findOrFail($id);

        if ($local->owner_id != $user->id)
            return redirect()->route('home');

        $local->delete();

        return redirect()->route('local.index');
    }
}

resources/views/commons/province.blade.php
<select class="form-control" name="{{ $name }}">
    <option value="{{ $default_value }}">Provincia</option>

    @php

    $provinces = [
        "AG" => 'Agrigento',
        "AL" => 'Alessandria',
        "AN" => 'Ancona',
        "AO" => 'Aosta',
        "AR" => 'Arezzo',
        "AP" => 'Ascoli Piceno',
        "AT" => 'Asti',
        "AV" => 'Avellino',
        "BA" => 'Bari',
        "BT" => 'Barletta-Andria-Trani',
        "BL" => 'Belluno',
        "BN" => 'Benevento',
        "BG" => 'Bergamo',
        "BI" => 'Biella',
        "BO" => 'Bologna',
        "BZ" => 'Bolzano',
        "BS" => 'Brescia',
        "BR" => 'Brindisi',
        "CA" => 'Cagliari',
        "CL" => 'Caltanissetta',
        "CB" => 'Campobasso',
        "CI" => 'Carbonia-Iglesias',
        "CE" => 'Caserta',
        "CT" => 'Catania',
        "CZ" => 'Catanzaro',
        "CH" => 'Chieti',
        "CO" => 'Como',
        "CS" => 'Cosenza',
        "CR" => 'Cremona',
        "KR" => 'Crotone',
        "CN" => 'Cuneo',
        "EN" => 'Enna',
        "FM" => 'Fermo',
        "FE" => 'Ferrara',
        "FI" => 'Firenze',
        "FG" => 'Foggia',
        "FC" => 'Forl&igrave;-Cesena',
        "FR" => 'Frosinone',
        "GE" => 'Genova',
        "GO" => 'Gorizia',
        "GR" => 'Grosseto',
        "IM" => 'Imperia',
        "IS" => 'Isernia',
        "SP" => 'La Spezia',
        "AQ" => 'L\'Aquila',
        "LT" => 'Latina',
        "LE" => 'Lecce',
        "LC" => 'Lecco',
        "LI" => 'Livorno',
        "LO" => 'Lodi',
        "LU" => 'Lucca',
        "MC" => 'Macerata',
        "MN" => 'Mantova',
        "MS" => 'Massa-Carrara',
        "MT" => 'Matera',
        "ME" => 'Messina',
        "MI" => 'Milano',
        "MO" => 'Modena',
        "MB" => 'Monza e della Brianza',
        "NA" => 'Napoli',
        "NO" => 'Novara',
        "NU" => 'Nuoro',
        "OT" => 'Olbia-Tempio',
        "OR" => 'Oristano',
        "PD" => 'Padova',
        "PA" => 'Palermo',
        "PR" => 'Parma',
        "PV" => 'Pavia',
        "PG" => 'Perugia',
        "PU" => 'Pesaro e Urbino',
        "PE" => 'Pescara',
        "PC" => 'Piacenza',
        "PI" => 'Pisa',
        "PT" => 'Pistoia',
        "PN" => 'Pordenone',
        "PZ" => 'Potenza',
        "PO" => 'Prato',
        "RG" => 'Ragusa',
        "RA" => 'Ravenna',
        "RC" => 'Reggio Calabria',
        "RE" => 'Reggio Emilia',
        "RI" => 'Rieti',
        "RN" => 'Rimini',
        "RM" => 'Roma',
        "RO" => 'Rovigo',
        "SA" => 'Salerno',
        "VS" => 'Medio Campidano',
        "SS" => 'Sassari',
        "SV" => 'Savona',
        "SI" => 'Siena',
        "SR" => 'Siracusa',
        "SO" => 'Sondrio',
        "TA" => 'Taranto',
        "TE" => 'Teramo',
        "TR" => 'Terni',
        "TO" => 'Torino',
        "OG" => 'Ogliastra',
        "TP" => 'Trapani',
        "TN" => 'Trento',
        "TV" => 'Treviso',
        "TS" => 'Trieste',
        "UD" => 'Udine',
        "VA" => 'Varese',
        "VE" => 'Venezia',
        "VB" => 'Verbano-Cusio-Ossola',
        "VC" => 'Vercelli',
        "VR" => 'Verona',
        "VV" => 'Vibo Valentia',
        "VI" => 'Vicenza',
        "VT" => 'Viterbo',
    ];

    if (!isset($selected))
        $selected = null;

    foreach($provinces as $plate => $name)
        echo sprintf('<option value="%s" %s>%s</option>', $plate, $selected && $selected == $plate ? 'selected' : '', $name);

    @endphp
</select>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
            <p>
                Ogni anno, ad inizio febbraio, circa 8000 tra sviluppatori, sistemisti ed addetti ai lavori si ritrovano a Bruxelles, in Belgio, per il <strong>Free Open Source Developers European Meeting</strong> (per gli amici: <a href="https://fosdem.org/">FOSDEM</a>), il principale convegno europeo dedicato al software libero e opensource.
            </p>
            <p>
                Non tutti riescono a partecipare, per motivi di studio o lavoro, ma vorremmo permettere a tutti di vivere almeno in parte l'"esperienza FOSDEM" pur restando nella propria città.
            </p>
            <h2>
                Quest'anno il FOSDEM è<br>
                <?php $dates = effectiveDates() ?>
                {{ $dates->saturday->printable }}<br>
                {{ $dates->sunday->printable }}<br>
            </h2>
            <br>
            <p>
                Problemi? Dubbi? Segnalazioni? Scrivi a <a href="mailto:webmaster@linux.it">webmaster@linux.it</a>!
            </p>
        </div>
        <div class="col-md-6">
            <div class="well">
                <p>
                    Organizza il <strong>FOSDEM Extended</strong> nella tua città!
                </p>
                <p>
                    Ti serve:
                </p>
                <ul>
                    <li>una stanza abbastanza capiente (20/50 persone) che possa essere occupata sabato e/o domenica. Può andar bene una scuola, un ufficio, o un locale pubblico</li>
                    <li>buona connettività a internet</li>
                    <li>un proiettore, una superficie su cui proiettare, e delle casse audio</li>
                </ul>
                <p>
                    Autenticati e registra il tuo evento locale!
                </p>
            </div>
        </div>
    </div>

    <br><br>

    <div class="row">
        <div class="col-md-12 text-center">
            @if(Auth::check())
                <a class="btn btn-default btn-lg" href="{{ route('local.index') }}">Crea ed esplora eventi locali</a>
            @else
                <div class="btn-group" role="group">
                    <a class="btn btn-default btn-lg" href="{{ route('login') }}">Autenticati su Servizi.Linux.it</a>
                    <a class="btn btn-default btn-lg" href="{{ route('login.gitlab') }}">Autenticati con GitLab</a>
                    <a class="btn btn-default btn-lg" href="{{ route('login.facebook') }}">Autenticati con Facebook</a>
                </div>
            @endif
        </div>
    </div>
</div>
@endsection

resources/views/local/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <p>
                Per organizzare il FOSDEM Extended occorre avere:
            </p>
            <ul>
                <li>una stanza abbastanza capiente (20/50 persone) che possa essere occupata per tutto il weekend, sabato e domenica (oppure, alla peggio, solo sabato o solo domenica), entro gli orari del FOSDEM (dalle 9:00 alle 19:00, ma dipende anche dai talk che verranno selezionati dal tuo pubblico). Può andar bene una scuola, un ufficio, o un locale pubblico (un bar, un ristorante, una birreria...). Laddove possibile, e date le opportune risorse, puoi anche allestire più di una sala per poter avere più sessioni ed accontentare molte più persone che vogliono vedere talk diversi in contemporanea!</li>
                <li>buona connettività a internet: fare streaming audio/video tutto il giorno richiede una banda stabile!</li>
                <li>un proiettore, una superficie su cui proiettare, e delle casse audio</li>
            </ul>
            <p>
                Se hai tutti questi requisiti, registra qua sotto la tua istanza locale.
            </p>
        </div>
    </div>

    <br><br><br>

    <div class="row">
        <div class="col-md-12">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <form class="form-horizontal" method="POST" action="{{ route('local.store') }}">
                @csrf

                <div class="form-group">
                    <label class="col-sm-2 control-label">Mappa</label>
                    <div class="col-sm-10">
                        <div id="address_map"></div>
                        <input type="hidden" name="lng" value="{{ old('lng') }}" required>
                        <input type="hidden" name="lat" value="{{ old('lat') }}" required>
                        <span class="help-block">Clicca e trascina il marker sulla mappa per selezionare il punto che apparirà sulla mappa.</span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="province" class="col-sm-2 control-label">Provincia</label>
                    <div class="col-sm-10">
                        @include('commons.province', ['name' => 'province', 'default_value' => ''])
                    </div>
                </div>

                <div class="form-group">
                    <label for="city" class="col-sm-2 control-label">Città</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="city" value="{{ old('city') }}">
                    </div>
                </div>

                <div class="form-group">
                    <label for="days" class="col-sm-2 control-label">Giorni</label>
                    <div class="col-sm-10">
                        <div class="btn-group" data-toggle="buttons">
                            <label class="btn btn-primary active">
                                <input type="radio" name="days" id="both" value="both" autocomplete="off" checked> Sabato e Domenica
                            </label>
                            <label class="btn btn-primary">
                                <input type="radio" name="days" id="saturday" value="saturday" autocomplete="off"> Solo Sabato
                            </label>
                            <label class="btn btn-primary">
                                <input type="radio" name="days" id="sunday" value="sunday" autocomplete="off"> Solo Domenica
                            </label>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="address" class="col-sm-2 control-label">Indirizzo</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="address" value="{{ old('address') }}">
                    </div>
                </div>

                <div class="form-group">
                    <label for="description" class="col-sm-2 control-label">Descrizione</label>
                    <div class="col-sm-10">
                        <textarea class="form-control" name="description">{{ old('description') }}</textarea>
                        <span class="help-block">Per il pranzo, tutti mettono 5 euro e qualcuno va a prendere delle pizze? Scrivilo qui! Occorrono indicazioni specifiche per raggiungere il posto (e.g. "Citofonare Mario")? Scrivilo qui! Intendete tenere una sessione speciale per guardare tutti i talk della devroom dedicata a BSD? Scrivilo qui!</span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="rooms" class="col-sm-2 control-label">Sale Disponibili</label>
                    <div class="col-sm-10">
                        <input type="number" class="form-control" name="rooms" step="1" min="1" value="1">
                    </div>
                </div>

                <div class="form-group">
                    <label for="rooms" class="col-sm-2 control-label">Devroom Selezionate</label>
                    <div class="col-sm-10">
                        <p>
                            Se hai degli interessi particolari e specifici, seleziona qui le devroom che intendi seguire durante il tuo FOSDEM Extended (<a href="https://fosdem.org/{{ env('CURRENT_YEAR') }}/schedule/" target="_blank">qui trovi il programma completo</a>, coi relativi talks). Se non ne selezioni nessuna, si assume che i talk da vedere insieme saranno decisi sul momento dai partecipanti.
                        </p>

                        @foreach(App\Devroom::where('year', env('CURRENT_YEAR'))->orderBy('title')->get() as $devroom)
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="devroom[]" value="{{ $devroom->id }}"> {{ $devroom->title }}
                                </label>
                            </div>
                        @endforeach
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-success">Registra evento</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@include('local.extraedit')

@endsection

resources/views/local/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <form class="form-horizontal" method="POST" action="{{ route('local.update', $local->id) }}">
                @csrf
                @method('PUT')

                <div class="form-group">
                    <label class="col-sm-2 control-label">Mappa</label>
                    <div class="col-sm-10">
                        <div id="address_map"></div>
                        <input type="hidden" name="lng" value="{{ $local->lng }}" required>
                        <input type="hidden" name="lat" value="{{ $local->lat }}" required>
                        <span class="help-block">Clicca e trascina il marker sulla mappa per selezionare il punto che apparirà sulla mappa.</span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="province" class="col-sm-2 control-label">Provincia</label>
                    <div class="col-sm-10">
                        @include('commons.province', ['name' => 'province', 'default_value' => '', 'selected' => $local->province])
                    </div>
                </div>

                <div class="form-group">
                    <label for="city" class="col-sm-2 control-label">Città</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="city" value="{{ $local->city }}">
                    </div>
                </div>

                <div class="form-group">
                    <label for="days" class="col-sm-2 control-label">Giorni</label>
                    <div class="col-sm-10">
                        <div class="btn-group" data-toggle="buttons">
                            <label class="btn btn-primary {{ $local->has_saturday && $local->has_sunday ? 'active' : '' }}">
                                <input type="radio" name="days" id="both" value="both" autocomplete="off" {{ $local->has_saturday && $local->has_sunday ? 'checked' : '' }}> Sabato e Domenica
                            </label>
                            <label class="btn btn-primary {{ $local->has_saturday && $local->has_sunday == false ? 'active' : '' }}">
                                <input type="radio" name="days" id="saturday" value="saturday" autocomplete="off" {{ $local->has_saturday && $local->has_sunday == false ? 'checked' : '' }}> Solo Sabato
                            </label>
                            <label class="btn btn-primary {{ $local->has_saturday == false && $local->has_sunday ? 'active' : '' }}">
                                <input type="radio" name="days" id="sunday" value="sunday" autocomplete="off" {{ $local->has_saturday == false && $local->has_sunday ? 'checked' : '' }}> Solo Domenica
                            </label>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="address" class="col-sm-2 control-label">Indirizzo</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="address" value="{{ $local->address }}">
                    </div>
                </div>

                <div class="form-group">
                    <label for="description" class="col-sm-2 control-label">Descrizione</label>
                    <div class="col-sm-10">
                        <textarea class="form-control" name="description">{{ $local->description }}</textarea>
                    </div>
                </div>

                <div class="form-group">
                    <label for="rooms" class="col-sm-2 control-label">Sale Disponibili</label>
                    <div class="col-sm-10">
                        <input type="number" class="form-control" name="rooms" step="1" min="1" value="{{ $local->rooms }}">
                    </div>
                </div>

                <div class="form-group">
                    <label for="rooms" class="col-sm-2 control-label">Devroom Selezionate</label>
                    <div class="col-sm-10">
                        @foreach(App\Devroom::where('year', $local->year)->orderBy('title')->get() as $devroom)
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="devroom[]" value="{{ $devroom->id }}" {{ $local->devrooms()->where('devroom_id', $devroom->id)->count() == 0 ? '' : 'checked' }}> {{ $devroom->title }}
                                </label>
                            </div>
                        @endforeach
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-success">Salva evento</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@include('local.extraedit')

@endsection

resources/views/local/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
            <h2>{{ $local->city }} ({{ $local->province }})</h2>
            <h3>{{ $local->address }}</h3>

            <?php $dates = effectiveDates() ?>
            <h4>
                @if($local->has_saturday && $local->has_sunday)
                    {{ $dates->saturday->printable }} e {{ $dates->sunday->printable }}
                @elseif($local->has_saturday)
                    {{ $dates->saturday->printable }}
                @elseif($local->has_sunday)
                    {{ $dates->sunday->printable }}
                @endif
            </h4>

            @if($local->year == env('CURRENT_YEAR'))
                @if($user && $user->id == $local->owner->id)
                    <form method="POST" action="{{ route('local.destroy', $local->id) }}">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger">Elimina evento</button>
                    </form>
                    <a class="btn btn-default" href="{{ route('local.edit', $local->id) }}">Modifica evento</a>
                @endif
            @endif

            <hr>

            <p>
                {!! htmlize($local->description) !!}
            </p>
        </div>

        <div class="col-md-6">
            <div id="address_map"></div>
        </div>
    </div>

    <br><br><br>

    <?php $devrooms = $local->devrooms ?>
    <div class="row">
        <div class="col-md-12">
            @if($devrooms->isEmpty())
                <div class="alert alert-info">
                    Questo evento locale non ha devroom selezionate: i talk da seguire saranno scelti sul momento dai partecipanti!
                </div>
            @else
                <p>
                    Gli organizzatori di questo evento locale hanno selezionato le seguenti devroom, che saranno seguite nel corso della/e giornata/e:
                </p>
                <table>
                    <tbody>
                        @foreach($devrooms as $devroom)
                            <tr>
                                <td>{{ $devroom->title }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @endif
        </div>
    </div>
</div>

<style>
#address_map {
    width: 100%;
    height: 300px;
}
</style>

<script>
    var lng = {{ $local->lng }};
    var lat = {{ $local->lat }};

    mapboxgl.accessToken = 'pk.eyJ1IjoibWFkYm9iIiwiYSI6ImNqa2JsdnJqYzB5cHQzcHBkOWI0dTZ4OWMifQ.tnQnu1GuUnt1k3QvPqwe0w';
    var map = new mapboxgl.Map({
        container: 'address_map',
        style: 'mapbox://styles/mapbox/streets-v9',
        center: [lng, lat],
        zoom: 12,
        maxBounds: [
            [0.626, 34.633],
            [25.871, 47.821]
        ]
    });

    var marker = new mapboxgl.Marker().setLngLat([lng, lat]).addTo(map);
</script>
@endsection